/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BgmRequest {
    alignment?: string;

    tree?: string;

    /**
     * Specify branches to test
     */
    branches?: string;

    genetic_code?: models.GeneticCode;

    /**
     * The type of data being analyzed
     */
    data_type?: BgmRequest.DataTypeEnum;

    /**
     * Number of MCMC steps to sample
     */
    steps?: number;

    /**
     * Number of MCMC steps to discard as burn-in
     */
    burn_in?: number;

    /**
     * Number of samples to extract from the chain
     */
    samples?: number;

    /**
     * Maximum number of parents allowed per node
     */
    max_parents?: number;

    /**
     * Minimum number of substitutions per site to include in the analysis
     */
    min_subs?: number;

}
export namespace BgmRequest {
    export enum DataTypeEnum {
        Nucleotide = <any> 'nucleotide',
        AminoAcid = <any> 'amino-acid',
        Codon = <any> 'codon'
    }
}
