/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BustedResultResult {
    analysis?: models.AnalysisInfo;

    input?: models.InputInfo;

    tested?: { [key: string]: { [key: string]: string; }; };

    timers?: { [key: string]: models.TimersInfoValue; };

    runtime?: string;

    data_partitions?: { [key: string]: models.PartitionsInfoValue; };

    background?: number;

    fits?: { [key: string]: models.BustedResultResultAllOfFitsValue; };

    branch_attributes?: models.BustedResultResultAllOfBranchAttributes;

    test_results?: models.BustedResultResultAllOfTestResults;

    substitutions?: { [key: string]: { [key: string]: models.BustedResultResultAllOfSubstitutionsValueValue; }; };

    Synonymous_site_posteriors?: Array<Array<number>>;

    Site_Log_Likelihood?: models.BustedResultResultAllOfSiteLogLikelihood;

    Evidence_Ratios?: models.BustedResultResultAllOfEvidenceRatios;

}
export namespace BustedResultResult {
    export enum TestedEnum {
        Tested = <any> 'tested',
        Background = <any> 'background'
    }
}
