/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface GardResultResult {
    analysis?: models.AnalysisInfo;

    input?: models.InputInfo;

    tested?: { [key: string]: { [key: string]: string; }; };

    timers?: { [key: string]: models.TimersInfoValue; };

    runtime?: string;

    data_partitions?: { [key: string]: models.PartitionsInfoValue; };

    /**
     * Baseline score for the analysis
     */
    baselineScore?: number;

    /**
     * Number of potential breakpoints analyzed
     */
    potentialBreakpoints?: number;

    /**
     * AICc score for the single tree model
     */
    singleTreeAICc?: number;

    /**
     * Time elapsed for the analysis in seconds
     */
    timeElapsed?: number;

    /**
     * Total number of models evaluated
     */
    totalModelCount?: number;

    /**
     * Data for each segment between breakpoints
     */
    breakpointData?: { [key: string]: models.GardResultResultAllOfBreakpointDataValue; };

    /**
     * Improvement metrics for each breakpoint
     */
    improvements?: { [key: string]: models.GardResultResultAllOfImprovementsValue; };

    /**
     * Support values for potential breakpoints at each site
     */
    siteBreakPointSupport?: { [key: string]: number; };

    /**
     * Tree data
     */
    trees?: { [key: string]: object; };

}
export namespace GardResultResult {
    export enum TestedEnum {
        Tested = <any> 'tested',
        Background = <any> 'background'
    }
}
