/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface GardRequest {
    alignment?: string;

    genetic_code?: models.GeneticCode;

    /**
     * The type of data being analyzed
     */
    data_type?: GardRequest.DataTypeEnum;

    /**
     * The optimization mode
     */
    run_mode?: GardRequest.RunModeEnum;

    /**
     * Specifies the model for rate variation among sites
     */
    site_to_site_variation?: GardRequest.SiteToSiteVariationEnum;

    /**
     * The number of discrete rate classes for rate variation
     */
    rate_classes?: number;

    /**
     * The substitution model to use
     */
    model?: string;

}
export namespace GardRequest {
    export enum DataTypeEnum {
        Nucleotide = <any> 'Nucleotide',
        Protein = <any> 'Protein'
    }
    export enum RunModeEnum {
        Normal = <any> 'Normal',
        Faster = <any> 'Faster'
    }
    export enum SiteToSiteVariationEnum {
        None = <any> 'None',
        GeneralDiscrete = <any> 'General Discrete',
        BetaGamma = <any> 'Beta-Gamma'
    }
}
