/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Statistical test results comparing different models
 */
export interface MultihitResultResultTestResults {
    Double_hit_vs_single_hit?: models.MultihitResultResultTestResultsDoubleHitVsSingleHit;

    Triple_hit_vs_Triple_hit_island?: models.MultihitResultResultTestResultsDoubleHitVsSingleHit;

    Triple_hit_vs_double_hit?: models.MultihitResultResultTestResultsDoubleHitVsSingleHit;

    Triple_hit_vs_single_hit?: models.MultihitResultResultTestResultsDoubleHitVsSingleHit;

    Triple_hit_island_vs_double_hit?: models.MultihitResultResultTestResultsDoubleHitVsSingleHit;

}
