/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Evidence ratios for different substitution types
 */
export interface MultihitResultResultEvidenceRatios {
    /**
     * Evidence ratios for three-hit substitutions
     */
    three_hit?: Array<Array<number>>;

    /**
     * Evidence ratios for two-hit substitutions
     */
    two_hit?: Array<Array<number>>;

    /**
     * Evidence ratios comparing three-hit islands vs two-hit substitutions
     */
    three_hit_islands_vs_2_hit?: Array<Array<number>>;

}
