/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RelaxResultResultAllOfTestResultsBranchAttributesValueValue {
    original_name?: string;

    Nucleotide_GTR?: number;

    MG94xREV_with_separate_rates_for_branch_sets?: number;

    General_descriptive?: number;

    k__general_descriptive?: number;

    RELAX_null?: number;

    RELAX_alternative?: number;

    k__RELAX_alternative?: number;

    tested?: boolean;

}
