/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Timing information for the analysis
 */
export interface SlacResultResultTimers {
    Total_time?: models.AbsrelResultResultAllOfTimersValue;

    Model_fitting?: models.AbsrelResultResultAllOfTimersValue;

    Primary_SLAC_analysis?: models.AbsrelResultResultAllOfTimersValue;

    Ancestor_sampling_analysis?: models.AbsrelResultResultAllOfTimersValue;

}
