/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ContrastFelResultResult {
    input?: models.ContrastFelResultResultInput;

    analysis?: models.ContrastFelResultResultAnalysis;

    /**
     * Mapping of branch names to their test groups (e.g., \"TREATED\", \"NAIVE\", \"background\")
     */
    tested?: { [key: string]: string; };

    MLE?: models.ContrastFelResultResultMLE;

    /**
     * Attributes for each branch in the phylogenetic tree
     */
    branch_attributes?: { [key: string]: object; };

    /**
     * Model fit statistics
     */
    fits?: { [key: string]: object; };

}
