/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface FelRequest {
    alignment?: string;

    tree?: string;

    /**
     * Compute confidence intervals for estimated rates
     */
    ci?: FelRequest.CiEnum;

    /**
     * Include synonymous rate variation in the model
     */
    srv?: FelRequest.SrvEnum;

    /**
     * Number of bootstrap resamples
     */
    resample?: number;

    /**
     * Specify handling of multiple nucleotide substitutions
     */
    multiple_hits?: FelRequest.MultipleHitsEnum;

    /**
     * Specify whether to estimate multiple hit rates for each site
     */
    site_multihit?: FelRequest.SiteMultihitEnum;

    genetic_code?: models.GeneticCode;

    /**
     * Branches to include in the analysis. If empty, all branches are included.
     */
    branches?: Array<string>;

}
export namespace FelRequest {
    export enum CiEnum {
        Yes = <any> 'Yes',
        No = <any> 'No'
    }
    export enum SrvEnum {
        Yes = <any> 'Yes',
        No = <any> 'No'
    }
    export enum MultipleHitsEnum {
        None = <any> 'None',
        Double = <any> 'Double',
        DoubleTriple = <any> 'Double+Triple'
    }
    export enum SiteMultihitEnum {
        Estimate = <any> 'Estimate',
        Global = <any> 'Global'
    }
}
