/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface AbsrelRequest {
    alignment?: string;

    tree?: string;

    /**
     * Include synonymous rate variation in the model
     */
    srv?: AbsrelRequest.SrvEnum;

    /**
     * Specify handling of multiple nucleotide substitutions
     */
    multiple_hits?: AbsrelRequest.MultipleHitsEnum;

    genetic_code?: models.GeneticCode;

    /**
     * Branches to include in the analysis. If empty, all branches are included.
     */
    branches?: Array<string>;

    /**
     * Bag of little bootstrap alignment resampling rate
     */
    blb?: number;

}
export namespace AbsrelRequest {
    export enum SrvEnum {
        Yes = <any> 'Yes',
        No = <any> 'No'
    }
    export enum MultipleHitsEnum {
        None = <any> 'None',
        Double = <any> 'Double',
        DoubleTriple = <any> 'Double+Triple'
    }
}
