/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Available Genetic Codes 
 */
    /**
    * Available Genetic Codes 
    */
export enum GeneticCode {
    Universal = <any> 'Universal',
    VertebrateMtDna = <any> 'Vertebrate mtDNA',
    YeastMtDna = <any> 'Yeast mtDNA',
    MoldProtozoanMtDna = <any> 'Mold/Protozoan mtDNA',
    InvertebrateMtDna = <any> 'Invertebrate mtDNA',
    CiliateNuclear = <any> 'Ciliate Nuclear',
    EchinodermMtDna = <any> 'Echinoderm mtDNA',
    EupltoidNuclear = <any> 'Eupltoid Nuclear',
    AltYeastNuclear = <any> 'Alt. Yeast Nuclear',
    AscidianMtDna = <any> 'Ascidian mtDNA',
    FlatwormMtDna = <any> 'Flatworm mtDNA',
    BlepharismaNuclear = <any> 'Blepharisma Nuclear'
}
