/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Request parameters for MULTI-HIT analysis
 */
export interface MultihitRequest {
    /**
     * Path to the alignment file (e.g., .fasta, .phy)
     */
    alignment_file: string;

    /**
     * The genetic code to use for the analysis
     */
    genetic_code: string;

    /**
     * Toggle for accounting synonymous triple-hit substitutions
     */
    triple_islands?: MultihitRequest.TripleIslandsEnum;

    /**
     * Number of rate classes to use
     */
    rate_classes?: number;

}
export namespace MultihitRequest {
    export enum TripleIslandsEnum {
        Yes = <any> 'Yes',
        No = <any> 'No'
    }
}
