/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RelaxRequest {
    alignment?: string;

    tree?: string;

    genetic_code?: models.GeneticCode;

    /**
     * Branches to be considered as \'Test\'
     */
    test_branches?: Array<string>;

    /**
     * Branches to be considered as \'Reference\'
     */
    reference_branches?: Array<string>;

    /**
     * Type of analysis to run (All for descriptive models and RELAX test, Minimal for only the RELAX test)
     */
    models?: RelaxRequest.ModelsEnum;

    /**
     * Number of omega rate classes
     */
    rates?: number;

    /**
     * Specify whether to handle zero-length branches
     */
    kill_zero_lengths?: RelaxRequest.KillZeroLengthsEnum;

}
export namespace RelaxRequest {
    export enum ModelsEnum {
        All = <any> 'All',
        Minimal = <any> 'Minimal'
    }
    export enum KillZeroLengthsEnum {
        Yes = <any> 'Yes',
        No = <any> 'No'
    }
}
