/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RelaxResultResultAllOfTestResults {
    p_value?: number;

    relaxation_or_intensification_parameter?: number;

    test?: string;

    alternative?: string;

    _null?: string;

    background?: string;

    log_likelihood_ratio?: number;

    degrees_of_freedom?: number;

    branch_attributes?: { [key: string]: { [key: string]: models.RelaxResultResultAllOfTestResultsBranchAttributesValueValue; }; };

}
