/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface SlacResultResultBranchAttributesValueValue {
    original_name?: string;

    Nucleotide_GTR?: number;

    Global_MG94xREV?: number;

    codon?: Array<Array<string>>;

    amino_acid?: Array<Array<string>>;

    synonymous_substitution_count?: Array<Array<number>>;

    nonsynonymous_substitution_count?: Array<Array<number>>;

}
