/**
 * Datamonkey API
 * Datamonkey is a free public server for comparative analysis of sequence alignments using state-of-the-art statistical models. <br> This is the OpenAPI definition for the Datamonkey API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: spond@temple.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface SlacResultResult {
    analysis?: models.SlacResultResultAnalysis;

    fits?: models.SlacResultResultFits;

    timers?: models.SlacResultResultTimers;

    /**
     * Branches tested in the analysis
     */
    tested?: { [key: string]: { [key: string]: string; }; };

    input?: models.SlacResultResultInput;

    /**
     * Data partitions used in the analysis
     */
    data_partitions?: { [key: string]: models.PartitionsInfoValue; };

    /**
     * Branch-specific attributes
     */
    branch_attributes?: { [key: string]: { [key: string]: models.SlacResultResultBranchAttributesValueValue; }; };

    /**
     * Site-specific results
     */
    site_results?: { [key: string]: Array<number>; };

}
