export * from './ABSRELApi';
import { ABSRELApi } from './ABSRELApi';
export * from './BGMApi';
import { BGMApi } from './BGMApi';
export * from './BUSTEDApi';
import { BUSTEDApi } from './BUSTEDApi';
export * from './CONTRASTFELApi';
import { CONTRASTFELApi } from './CONTRASTFELApi';
export * from './FELApi';
import { FELApi } from './FELApi';
export * from './FUBARApi';
import { FUBARApi } from './FUBARApi';
export * from './FileUploadAndQCApi';
import { FileUploadAndQCApi } from './FileUploadAndQCApi';
export * from './GARDApi';
import { GARDApi } from './GARDApi';
export * from './HealthApi';
import { HealthApi } from './HealthApi';
export * from './MEMEApi';
import { MEMEApi } from './MEMEApi';
export * from './MULTIHITApi';
import { MULTIHITApi } from './MULTIHITApi';
export * from './RELAXApi';
import { RELAXApi } from './RELAXApi';
export * from './SLACApi';
import { SLACApi } from './SLACApi';
export const APIS = [ABSRELApi, BGMApi, BUSTEDApi, CONTRASTFELApi, FELApi, FUBARApi, FileUploadAndQCApi, GARDApi, HealthApi, MEMEApi, MULTIHITApi, RELAXApi, SLACApi];
